version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    volumes:
      - mongo-storage:/data/db

# Définition des volumes:
volumes:
  mongo-storage:
    driver: local
